import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import MenuIcon from '@mui/icons-material/Menu';
import ButtonAppBar from '@/components/Nav';
import {Head} from 'next/document';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <Head> */}
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
          crossOrigin="anonymous"
        />
      </head>
      {/* </Head> */}
      <body>
        {/* <ButtonAppBar/> */}

        <main className="app">
          {children}
        </main>
        </body>
    </html>
  )
}
